#!/bin/sh
#
# @name Generic Hexarotor x geometry
#
# @type Hexarotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
#

sh /etc/init.d/rc.mc_defaults

if [ ${AUTOCNF} = yes -o ${NEW_DEFAULTS} = yes ]
then
	param set MAV_TYPE 13

	#
	# Control parameters setting for TAP
	#
	# TAP v2
	# pitch angle & rate setting
	param set MC_PITCHRATE_P 0.12
	param set MC_PITCHRATE_I 0.08
	param set MC_PITCHRATE_D 0.001
	param set MC_PITCHRATE_MAX 120
	param set MC_PITCH_P 5.0

	# roll angle & rate setting
	param set MC_ROLLRATE_P 0.12
	param set MC_ROLLRATE_I 0.08
	param set MC_ROLLRATE_D 0.001
	param set MC_ROLLRATE_MAX 120
	param set MC_ROLL_P 5.0

	# yaw angle & rate setting
	param set MC_YAWRATE_P 0.2
	param set MC_YAWRATE_I 0.0575
	param set MC_YAWRATE_D 0.001
	param set MC_YAWRATE_MAX 80
	param set MC_YAWRAUTO_MAX 80
	param set MC_YAW_P 5.5

	# hover thrust
	param set MPC_THR_HOVER 0.45

	# Position control parameters
	param set MPC_XY_P 1.2
	param set MPC_XY_VEL_P 0.12
	param set MPC_XY_VEL_D 0.01
	param set MPC_XY_VEL_I 0.02
	param set MPC_Z_VEL_P 0.25
	param set MPC_Z_P 1.0
	param set MPC_Z_VEL_D 0
	param set MPC_Z_VEL_I 0.085
	param set MPC_VEL_MAN_UP 3
	param set MPC_TKO_RAMP_T 0.5

	# Manual stick input parameters
	param set RC_FLT_SMP_RATE 33
	param set RC_FLT_CUTOFF 5
	param set MPC_HOLD_DZ 0.1
	param set MPC_XY_MAN_EXPO 0.7
	param set MPC_Z_MAN_EXPO 0.6
	param set MPC_YAW_EXPO 0.6
	param set MPC_MANTHR_MIN 0.15
	param set MPC_MAN_Y_MAX 100

	# Position control velocity
	param set MPC_XY_CRUISE 10
	param set MPC_CRUISE_90 3
	param set MPC_XY_VEL_MAX 14
	param set MPC_Z_VEL_MAX_UP 3
	param set MPC_Z_VEL_MAX_DN 2.5
	param set MPC_LAND_SPEED 0.8
	param set MPC_LAND_ALT1 10
	param set MPC_LAND_ALT2	5
	param set MPC_VEL_MANUAL 10

	# Airmode for roll and pitch
	param set MC_AIRMODE 1

	# Position control acceleraton
	param set MPC_ACC_HOR_MAX 10
	param set MPC_ACC_HOR 6
	param set MPC_DEC_HOR_SLOW 1
	param set MPC_ACC_DOWN_MAX 2.0
	param set MPC_ACC_UP_MAX 3.0
	param set MPC_JERK_MAX 8.0
	param set MPC_JERK_MIN 0.1
	param set MPC_AUTO_MODE 0

	# Throttle pid attenuation
	param set MC_TPA_RATE_P 0.8
	param set MC_TPA_RATE_I 0.5
	param set MC_TPA_RATE_D 0.2
	param set MC_TPA_BREAK_P 0.45
	param set MC_TPA_BREAK_I 0.6
	param set MC_TPA_BREAK_D 0.65

	# FTC control parameters
	param set PROPELL_REV_COEF 1.1
	param set FTC_ROLLRATE_P 0.1
	param set FTC_ROLLRATE_I 0.08
	param set FTC_PITCHRATE_P 0.1
	param set FTC_PITCHRATE_I 0.08
	param set FTC_YAWRATE_P 0.16
	param set FTC_YAWRATE_I 0.09

	# Battery settings. Base on battery vendor and real fly testing log.
	# Change log: H920E 2020-07-07

	param set BAT_V_EMPTY 3.58
	param set BAT_V_CHARGED 4.35
	param set BAT_V_LOAD_DROP 0.1

	# H920E not enable current sensor yet. disable current related param.
	param set BAT_CAPACITY -1.0
	param set BAT_R_INTERNAL -1.0

	param set BAT_LOW_THR 0.20
	param set BAT_CRIT_THR 0.18
	param set BAT_EMERGEN_THR 0.05

	# RC
	param set COM_RC_OVERRIDE 1
	param set COM_RC_LOSS_T 3
	param set COM_DL_LOSS_T 10
	param set COM_ARM_STK_TOL 0.08
	param set COM_ARM_SWISBTN 1

	# allow receiving team mode input
	param set RC_LINK_MODE 3

	# set aux-button to flexi-release
	param set RCMAP_AUX 2

	# Altitude (manual) mode parameters
	param set MPC_MAN_TILT_MAX 24

	# Gyro already temperature calibrated and ID constant
	if ver hwcmp YUNEEC_TAP_V2
	then
		param set CAL_GYRO0_ID 3670290
	fi

	# Commander
	param set COM_DISARM_LAND 0.1
	param set COM_ARM_WO_GPS 1
	param set COM_INDR_OR_HOME 1

	#
	# Throttle max/min setting
	#
	param set MPC_THR_MAX 0.8
	param set MPC_THR_MIN 0.1

	#
	# RTL settings
	#
	param set RTL_LAND_DELAY 3.5
	param set LAND_LOI_DELAY 3.5

	#
	# Mission settings
	#
	param set MIS_YAW_ERR 90.0
	param set MIS_DIST_WPS 4000
	param set MIS_DIST_1WP 4000
	param set MIS_MNT_YAW_CTL 1

	#
	# Vehicle model settings
	#
	param set LNDMC_ALT_MAX 500

	#
	# Maximum tilt angle
	#
	param set MPC_TILTMAX_AIR 25

	#
	# Battery setting
	#
	param set BAT_N_CELLS 6

	#
	# Acceptance radius
	#
	param set NAV_ACC_RAD 1

	#
	# Calibrate by rotating around arms
	#
	param set CAL_MAG_METHOD 1

	#
	# Enable automatic gear deployment
	#
	param set MPC_GEAR_AUTO 1

	#
	# Flight modes
	#
	# Altitude hold
	param set COM_FLTMODE1 1
	# Position
	param set COM_FLTMODE2 2
	# RTL
	param set COM_FLTMODE3 5

	#
	# ST16 RC channel configuration
	#
	# remote control station type set to ST16
	param set RC_TYPE 1

	# Ekf2 wind speed compensation
	param set EKF2_PCOEF_XP -0.20
	param set EKF2_PCOEF_XN -0.20
	param set EKF2_PCOEF_Y -0.20
	param set EKF2_BARO_NOISE 3.0

	# Cutoff frequency for the low pass filter on the D-term in the rate controller
	param set MC_DTERM_CUTOFF 35

	# Driver level cutoff frequency for gyro
	param set IMU_GYRO_CUTOFF 15

	# gimbal driver configuration
	param set MNT_MODE_IN 4
	param set MNT_MODE_OUT 1
	param set MNT_MAN_ROLL 0
	param set MNT_MAN_PITCH 2
	param set MNT_MAN_YAW 1

	# sensor thermal calibration
	param set SYS_CAL_TDEL 60
	param set SYS_CAL_ACC_TOL 1
	param set SYS_CAL_GYRO_TOL 0.1

	# Enable power circuit breaker
	# HOTFIX: This disables the preflight checks for 5v and 3.3v power rails
	# which are not available on YUNEEC_TAP_V2. Should find a better solution.
	param set CBRK_SUPPLY_CHK 0
	if ver hwcmp YUNEEC_TAP_V2
	then
		param set CBRK_AVIO_CHK 586987
	else
		param set CBRK_AVIO_CHK 0
	fi

	# Fault tolerant control
	# 0: disabled
	# 1: enabled
	param set FTC_ENABLE 1

	# Events
	param set EV_TSK_STAT_DIS 1
	param set EV_TSK_RC_LOSS 1
	param set EV_TSK_INV_GEAR 1

	# PWM output value for throw channel
	param set PWM_THROW_OFF -0.1
	param set PWM_THROW_ON  0.6

	#param set SDLOG_MODE 1

	# battery voltage not available yet
	param set CBRK_SUPPLY_CHK   894281
	param save
fi



#
# ESC driver
#
sleep 1

	if tap_esc start -d ${ESC_TTY} -n 6
    then
	else
		# Config could not be written or verified. ESCs won't function properly!
		echo "Failed to send ESC config - not starting the ESC driver"
	fi

set OUTPUT_MODE tap_esc
set MIXER hexa_x

# Need to set all 8 channels
set PWM_OUT 12345678
